from pathlib import Path
import json


BASE = Path("/root/workspace/query/leader_profiles")

ALL_DIMENSIONS = [
    "人格感召与魅力自我认知",
    "共同体代表性与身份领导",
    "认知复杂性与信息开放",
    "情绪调节与情绪使用方式",
    "他人信任与威胁知觉",
    "共同体边界意识与内群体优先",
    "权力主导与控制倾向",
    "参与协商与权力分享倾向",
    "决策介入时机与回避程度",
    "结构化推进与任务压强",
    "关系维护与人际关照",
    "组织建制与统筹能力取向",
    "政治斡旋与资源整合方式",
    "愿景建构与意义动员",
    "公共沟通与符号化表达",
    "秩序与安全优先观",
    "发展与绩效优先观",
    "公平与包容优先观",
    "自由、权利与参与优先观",
    "国家干预—市场关系观",
    "国家—社会边界与协作观",
    "国家能力与行政效能观",
    "治理知识与决策依据观",
    "程序—宪制合法性观",
    "绩效合法性观",
    "人民代表性与主体合法性观",
    "多元差异与冲突观",
    "共同体凝聚与整合观",
    "改革方向与变革节奏观",
    "传统—现代化关系观",
    "主权与自主性观",
    "对外合作—竞争取向",
    "国际秩序立场与外部责任观",
]


LEADERS = {
    "fidel_castro": {
        "leader_name": "菲德尔·卡斯特罗",
        "country": "古巴 / 革命后社会主义一党政体",
        "remark": "以 1959-1970 年革命建政与高强度群众动员阶段为主，必要时参考 1970-1990 年制度巩固和长期反美时期的稳定倾向。",
        "core_dims": [
            "共同体代表性与身份领导",
            "权力主导与控制倾向",
            "愿景建构与意义动员",
            "公共沟通与符号化表达",
            "国家干预—市场关系观",
            "改革方向与变革节奏观",
            "主权与自主性观",
        ],
        "reference_dims": [
            "人格感召与魅力自我认知",
            "他人信任与威胁知觉",
            "共同体边界意识与内群体优先",
            "组织建制与统筹能力取向",
            "秩序与安全优先观",
            "人民代表性与主体合法性观",
        ],
        "answers": {
            "L01": {"display_no": 1, "legacy_id": "4-1", "summary": "追随力更多来自个人而非职位", "tier": "reference", "value": 7, "period": "1959-1976年", "evidence_type": "群众集会、革命声望、同时代观察", "note": "其追随力高度依赖个人革命英雄形象与人格魅力。"},
            "L02": {"display_no": 2, "legacy_id": "4-2", "summary": "公开讲话能激发热情与共鸣", "tier": "reference", "value": 7, "period": "1959-1980年", "evidence_type": "长篇演说、群众动员、国际讲话", "note": "公开讲话感染力极强，是其最鲜明的统治工具之一。"},
            "L03": {"display_no": 3, "legacy_id": "19-1", "summary": "自认能代表群体核心", "tier": "core", "value": 7, "period": "1959-1976年", "evidence_type": "革命讲话、政权合法性叙事、群众动员", "note": "稳定把自己塑造成古巴人民与革命共同体的代表。"},
            "L04": {"display_no": 4, "legacy_id": "19-2", "summary": "主动塑造整体意识", "tier": "core", "value": 7, "period": "1959-1976年", "evidence_type": "群众组织、政治教育、国家仪式", "note": "持续强化革命共同体和整体身份意识。"},
            "L10": {"display_no": 10, "legacy_id": "17-1", "summary": "多数人是否可相信", "tier": "reference", "value": 2, "period": "1961-1990年", "evidence_type": "安全国家实践、对内警惕语言", "note": "总体并不以普遍信任社会成员为前提。"},
            "L11": {"display_no": 11, "legacy_id": "17-2", "summary": "不警惕就会被利用", "tier": "reference", "value": 7, "period": "1961-1990年", "evidence_type": "反颠覆治理、对美对内斗争语言", "note": "长期把警惕渗透和利用视为必要政治常识。"},
            "L12": {"display_no": 12, "legacy_id": "17-3", "summary": "只信任少数真正了解的人", "tier": "reference", "value": 6, "period": "1959-1990年", "evidence_type": "核心圈层决策、干部使用", "note": "对核心圈外人员保持明显距离和审慎。"},
            "L13": {"display_no": 13, "legacy_id": "18-1", "summary": "自己人与外人区分必要", "tier": "reference", "value": 6, "period": "1961-1990年", "evidence_type": "革命与反革命话语、敌我划分", "note": "清晰区分革命阵营与敌对力量。"},
            "L14": {"display_no": 14, "legacy_id": "18-2", "summary": "资源有限时优先自己人", "tier": "reference", "value": 6, "period": "1961-1990年", "evidence_type": "革命政权资源分配、政治忠诚逻辑", "note": "在生存压力下明显优先革命共同体和忠诚者。"},
            "L15": {"display_no": 15, "legacy_id": "5-1", "summary": "习惯主动接手局面", "tier": "core", "value": 7, "period": "1959-1990年", "evidence_type": "危机应对、最高决策方式、传记研究", "note": "重大事务高度依赖其个人直接主导。"},
            "L16": {"display_no": 16, "legacy_id": "5-3", "summary": "重要事项需亲自把关", "tier": "core", "value": 7, "period": "1959-1990年", "evidence_type": "政策审批、干部回忆、长期统治风格", "note": "对关键事务强烈不放心完全放手。"},
            "L17": {"display_no": 17, "legacy_id": "5-5", "summary": "信息由自己决定何时公开", "tier": "core", "value": 7, "period": "1959-1990年", "evidence_type": "宣传控制、危机信息管理、媒体体制", "note": "明显偏好由最高领导控制信息节奏与边界。"},
            "L26": {"display_no": 26, "legacy_id": "10-1", "summary": "靠制度流程而非个人盯事", "tier": "reference", "value": 3, "period": "1959-1976年", "evidence_type": "个人化统治与制度建设并存", "note": "虽建立制度，但实际运作长期离不开其个人介入。"},
            "L27": {"display_no": 27, "legacy_id": "10-4", "summary": "即使不在组织也能高效运转", "tier": "reference", "value": 3, "period": "1959-1990年", "evidence_type": "权力集中、继任问题、制度研究", "note": "理想上重视组织，但现实中体系长期围绕其个人运行。"},
            "L28": {"display_no": 28, "legacy_id": "10-5", "summary": "国家机器还是忠诚核心圈", "tier": "reference", "value": 2, "period": "1959-1976年", "evidence_type": "革命建政、核心圈掌控、干部政治", "note": "更接近依靠忠诚核心圈掌控局面，而非纯粹抽象制度机器。"},
            "L29": {"display_no": 29, "legacy_id": "10-6", "summary": "关键资源位置应掌握在最忠诚者手中", "tier": "reference", "value": 7, "period": "1959-1990年", "evidence_type": "干部任用、革命忠诚逻辑", "note": "把关键岗位掌握在政治可靠者手里视为政权稳定前提。"},
            "L33": {"display_no": 33, "legacy_id": "12-2", "summary": "先定统领全局方向", "tier": "core", "value": 7, "period": "1959-1970年", "evidence_type": "革命纲领、长期战略讲话", "note": "总是先给出革命方向，再要求政策服从总路线。"},
            "L34": {"display_no": 34, "legacy_id": "14-1", "summary": "让人感到事业有更大意义", "tier": "core", "value": 7, "period": "1959-1980年", "evidence_type": "公开演说、国际主义叙事、政治教育", "note": "把治理与斗争提升为历史使命和道德事业。"},
            "L35": {"display_no": 35, "legacy_id": "13-2", "summary": "公开立场联系价值原则", "tier": "core", "value": 7, "period": "1959-1990年", "evidence_type": "革命修辞、反帝话语、公开讲话", "note": "表达立场时高度依赖反帝、正义、牺牲等价值语言。"},
            "L36": {"display_no": 36, "legacy_id": "13-4", "summary": "重大事件抢先定义局势", "tier": "core", "value": 7, "period": "1959-1990年", "evidence_type": "危机讲话、媒体主导、政治框架设定", "note": "重大事件往往由其先给出官方解释与历史意义。"},
            "G01": {"display_no": 37, "legacy_id": "G1-2", "summary": "安全优先于其他投入", "tier": "reference", "value": 6, "period": "1961-1990年", "evidence_type": "国家安全体制、军事化治理", "note": "在长期对抗环境下明显强调安全优先。"},
            "G02": {"display_no": 38, "legacy_id": "G1-4", "summary": "有纪律的社会比充分自由更值得追求", "tier": "reference", "value": 7, "period": "1961-1990年", "evidence_type": "革命纪律、社会规训、政治讲话", "note": "持续把纪律、秩序和革命规范置于高度优先位置。"},
            "G03": {"display_no": 39, "legacy_id": "G1-5", "summary": "发展起步阶段应压缩异议空间", "tier": "reference", "value": 7, "period": "1961-1976年", "evidence_type": "一党化、政治压制、革命巩固", "note": "认为革命建政和现代化推进需要压缩公开异议空间。"},
            "G11": {"display_no": 47, "legacy_id": "G5-1", "summary": "国家应积极介入经济", "tier": "core", "value": 1, "period": "1959-1985年", "evidence_type": "国有化、计划经济、产业控制", "note": "明确主张国家深度控制经济命脉与发展方向。"},
            "G12": {"display_no": 48, "legacy_id": "G5-2", "summary": "缩小贫富差距是政府责任", "tier": "core", "value": 1, "period": "1959-1985年", "evidence_type": "再分配、福利扩张、革命平等主义", "note": "强烈主张通过国家力量压缩收入与地位差距。"},
            "G13": {"display_no": 49, "legacy_id": "G5-3", "summary": "关键行业应由国家掌控", "tier": "core", "value": 1, "period": "1959-1985年", "evidence_type": "战略资源国有化、经济体制设计", "note": "关键行业和战略资源应由国家牢牢掌控。"},
            "G24": {"display_no": 60, "legacy_id": "G11-2", "summary": "领导人须代表人民意愿利益", "tier": "reference", "value": 7, "period": "1959-1976年", "evidence_type": "革命人民主权叙事、公开讲话", "note": "强烈强调领导权威来自代表人民和革命利益。"},
            "G25": {"display_no": 61, "legacy_id": "G11-3", "summary": "国家大方向最终决定权属于人民", "tier": "reference", "value": 6, "period": "1959-1976年", "evidence_type": "人民主权话语、全民动员框架", "note": "语言上强调人民主体，但实际通常经由革命国家来体现。"},
            "G32": {"display_no": 68, "legacy_id": "G14-1", "summary": "现有体制有根本问题时应深层变革", "tier": "core", "value": 7, "period": "1953-1965年", "evidence_type": "革命建政、制度改造、土地与经济变革", "note": "显然偏向打破旧体制并进行结构性重构。"},
            "G33": {"display_no": 69, "legacy_id": "G14-3", "summary": "试点渐进还是窗口期快推", "tier": "core", "value": 6, "period": "1959-1970年", "evidence_type": "革命推进、制度改造节奏", "note": "更偏向在机会窗口出现时集中力量快速推进。"},
            "G34": {"display_no": 70, "legacy_id": "G14-5", "summary": "制度性问题情境选择", "tier": "core", "value": "D", "period": "1959-1968年", "evidence_type": "革命实践、激进社会改造", "note": "最接近打破旧框架并争取一步到位推行新方案。"},
            "G35": {"display_no": 71, "legacy_id": "G14-6", "summary": "稳定后仍不断发动新政治运动", "tier": "core", "value": 6, "period": "1960-1980年", "evidence_type": "持续动员、道德激励、社会改造", "note": "虽不同于毛式持续革命，但确有长期政治动员与社会改造倾向。"},
            "G38": {"display_no": 74, "legacy_id": "G16-1", "summary": "主权不可让渡", "tier": "core", "value": 7, "period": "1959-2000年", "evidence_type": "反美外交、国家独立话语、危机表态", "note": "把反干涉与主权独立视为绝对底线。"},
            "G39": {"display_no": 75, "legacy_id": "G16-4", "summary": "关键领域减少对外依赖", "tier": "core", "value": 7, "period": "1959-1990年", "evidence_type": "自力更生、战略独立、国家安全思维", "note": "持续强调关键领域应具备独立自主能力。"},
            "G40": {"display_no": 76, "legacy_id": "G16-5", "summary": "革命政权更重国内改造还是外部主权", "tier": "core", "value": 2, "period": "1960-1970年", "evidence_type": "国内社会改造与国际对抗并存", "note": "更偏向不断在国内推进新的社会改造和政治动员。"},
            "G41": {"display_no": 77, "legacy_id": "G16-6", "summary": "国家应成为独立力量中心", "tier": "core", "value": 6, "period": "1960-1990年", "evidence_type": "第三世界外交、非结盟姿态、主权话语", "note": "强烈拒绝完全融入由大国主导的秩序。"},
        },
    },
    "lee_kuan_yew": {
        "leader_name": "李光耀",
        "country": "新加坡 / 议会主导的一党优势政体",
        "remark": "以 1965-1990 年建国、工业化与国家建制阶段为主，必要时参考其晚年回忆与长期公共论述中的稳定倾向。",
        "core_dims": [
            "认知复杂性与信息开放",
            "结构化推进与任务压强",
            "组织建制与统筹能力取向",
            "政治斡旋与资源整合方式",
            "秩序与安全优先观",
            "发展与绩效优先观",
            "国家—社会边界与协作观",
        ],
        "reference_dims": [
            "权力主导与控制倾向",
            "关系维护与人际关照",
            "治理知识与决策依据观",
            "改革方向与变革节奏观",
            "传统—现代化关系观",
            "主权与自主性观",
        ],
        "answers": {
            "L05": {"display_no": 5, "legacy_id": "15-1", "summary": "争议问题常有多面", "tier": "core", "value": 6, "period": "1965-1990年", "evidence_type": "政策讲话、回忆录、务实治理论述", "note": "对复杂议题通常承认没有单一简单答案。"},
            "L06": {"display_no": 6, "legacy_id": "15-2", "summary": "能接受暂时无定论", "tier": "core", "value": 6, "period": "1965-1990年", "evidence_type": "政策试验、国际比较、长期规划", "note": "能在矛盾信息下暂时保留判断并继续观察。"},
            "L07": {"display_no": 7, "legacy_id": "15-3", "summary": "决策前主动了解反对意见", "tier": "core", "value": 6, "period": "1965-1990年", "evidence_type": "公务体系、国际比较、反复论证", "note": "重大决策前重视不利信息、比较资料与反方观点。"},
            "L08": {"display_no": 8, "legacy_id": "15-4", "summary": "改革宜先试点边做边改", "tier": "core", "value": 6, "period": "1965-1990年", "evidence_type": "政策试验、住房教育语言政策调整", "note": "相当接近先试行再扩展的治理方法。"},
            "L15": {"display_no": 15, "legacy_id": "5-1", "summary": "习惯主动接手局面", "tier": "reference", "value": 6, "period": "1965-1985年", "evidence_type": "建国决策、核心领导风格", "note": "在关键事务上明显偏强主导。"},
            "L16": {"display_no": 16, "legacy_id": "5-3", "summary": "重要事项需亲自把关", "tier": "reference", "value": 6, "period": "1965-1990年", "evidence_type": "干部回忆、政策审批、领导集中度", "note": "对国家关键方向通常要求自己亲自把关。"},
            "L17": {"display_no": 17, "legacy_id": "5-5", "summary": "信息由自己决定何时公开", "tier": "reference", "value": 6, "period": "1965-1990年", "evidence_type": "舆论管理、政治传播控制", "note": "较强地相信关键政治信息需要由领导层掌控节奏。"},
            "L22": {"display_no": 22, "legacy_id": "8-3", "summary": "重视截止日期与完成时限", "tier": "core", "value": 7, "period": "1965-1990年", "evidence_type": "官僚体系要求、执行文化、回忆录", "note": "高度强调时限、落实和行政执行效率。"},
            "L23": {"display_no": 23, "legacy_id": "8-4", "summary": "未达标会当面指出", "tier": "core", "value": 7, "period": "1965-1990年", "evidence_type": "干部管理、公开批评、组织文化", "note": "对未达标准者直接问责是其典型风格。"},
            "L24": {"display_no": 24, "legacy_id": "8-5", "summary": "目标定下后一级级压实", "tier": "core", "value": 7, "period": "1965-1990年", "evidence_type": "发展型国家治理、绩效链条、行政推进", "note": "极强的目标压强式推进特征。"},
            "L25": {"display_no": 25, "legacy_id": "9-4", "summary": "推进工作时考虑承受力", "tier": "reference", "value": 5, "period": "1965-1990年", "evidence_type": "政策渐进、社会整合考量", "note": "会考虑社会承受力，但通常不会让其压倒总体目标。"},
            "L26": {"display_no": 26, "legacy_id": "10-1", "summary": "靠制度流程管理组织", "tier": "core", "value": 7, "period": "1965-1990年", "evidence_type": "公务员制度、法制与流程设计", "note": "强烈偏好制度化和流程化管理。"},
            "L27": {"display_no": 27, "legacy_id": "10-4", "summary": "不在时组织也能高效运转", "tier": "core", "value": 7, "period": "1970-1990年", "evidence_type": "接班安排、官僚体系建设、机构治理", "note": "追求组织能够脱离个人而长期稳定运转。"},
            "L28": {"display_no": 28, "legacy_id": "10-5", "summary": "国家机器还是私人网络", "tier": "core", "value": 7, "period": "1965-1990年", "evidence_type": "建制国家论述、反裙带政治立场", "note": "明确偏向能长期按统一路线运转的国家机器。"},
            "L29": {"display_no": 29, "legacy_id": "10-6", "summary": "关键资源应在最忠诚者手中", "tier": "core", "value": 3, "period": "1965-1990年", "evidence_type": "制度化任用、精英甄别逻辑", "note": "重视可靠性，但更强调能力、制度和国家机器而非私人忠诚。"},
            "L30": {"display_no": 30, "legacy_id": "11-3", "summary": "先私下沟通再正式推出", "tier": "core", "value": 6, "period": "1965-1990年", "evidence_type": "党政协同、精英沟通、国际谈判", "note": "重大事项常先做好关键利益方协调。"},
            "L31": {"display_no": 31, "legacy_id": "11-4", "summary": "为关键支持愿意让步", "tier": "core", "value": 5, "period": "1965-1990年", "evidence_type": "联盟经营、现实妥协、政策平衡", "note": "会做实用让步，但通常不会在核心方向上大幅退让。"},
            "L32": {"display_no": 32, "legacy_id": "11-5", "summary": "善于整合有限资源", "tier": "core", "value": 7, "period": "1965-1990年", "evidence_type": "建国资源整合、外资与国家能力结合", "note": "极善于把有限资源和多方力量拉到同一国家目标上。"},
            "G01": {"display_no": 37, "legacy_id": "G1-2", "summary": "安全优先于其他投入", "tier": "core", "value": 6, "period": "1965-1990年", "evidence_type": "国家生存论述、治安和国防政策", "note": "把安全与社会稳定视为国家生存前提。"},
            "G02": {"display_no": 38, "legacy_id": "G1-4", "summary": "有纪律社会比充分自由但混乱更值得追求", "tier": "core", "value": 7, "period": "1965-1990年", "evidence_type": "公开讲话、治理理念、社会政策", "note": "长期主张纪律、秩序和规则优先于无边界自由。"},
            "G03": {"display_no": 39, "legacy_id": "G1-5", "summary": "发展起步阶段应压缩异议空间", "tier": "core", "value": 6, "period": "1965-1985年", "evidence_type": "一党优势治理、政治竞争控制", "note": "认为建国和现代化初期需要压缩高烈度政治冲突。"},
            "G04": {"display_no": 40, "legacy_id": "G2-2", "summary": "主要看成果而非程序规范", "tier": "core", "value": 6, "period": "1965-1990年", "evidence_type": "绩效合法性论述、治理评价标准", "note": "衡量领导人时明显偏重是否把事情做成。"},
            "G05": {"display_no": 41, "legacy_id": "G2-3", "summary": "经济搞不上去一切空谈", "tier": "core", "value": 7, "period": "1965-1990年", "evidence_type": "发展主义讲话、工业化实践", "note": "把经济发展视为国家生存与政治正当性的根本。"},
            "G14": {"display_no": 50, "legacy_id": "G6-1", "summary": "社会组织应在政府指导下运作", "tier": "core", "value": 2, "period": "1965-1990年", "evidence_type": "国家主导社团关系、治理架构", "note": "更偏向国家指导社会组织运行而非完全自治。"},
            "G15": {"display_no": 51, "legacy_id": "G6-2", "summary": "政府应引导道德与文化方向", "tier": "core", "value": 2, "period": "1965-1990年", "evidence_type": "社会工程、价值教育、文化政策", "note": "明确认为政府应积极塑造社会行为规范与价值风气。"},
            "G16": {"display_no": 52, "legacy_id": "G6-5", "summary": "公共事务由政府定方向还是共同决定", "tier": "core", "value": 2, "period": "1965-1990年", "evidence_type": "国家主导治理、协商但不平权分享", "note": "更接近政府定大方向，社会力量负责配合执行。"},
            "G17": {"display_no": 53, "legacy_id": "G6-6", "summary": "国家应长期塑造社会行为方式", "tier": "core", "value": 7, "period": "1965-1990年", "evidence_type": "公共纪律、住房与家庭政策、社会规范塑造", "note": "这是其治理哲学中的招牌特征。"},
            "G19": {"display_no": 55, "legacy_id": "G8-2", "summary": "有经验治理者靠直觉经验即可准确判断", "tier": "reference", "value": 4, "period": "1965-1990年", "evidence_type": "实战经验与数据并用、精英治理观", "note": "重视经验判断，但并不完全排斥证据与专业分析。"},
            "G20": {"display_no": 56, "legacy_id": "G8-4", "summary": "重大治理难题最依赖哪种知识来源", "tier": "reference", "value": "B", "period": "1965-1990年", "evidence_type": "精英治国观、核心团队决策实践", "note": "更接近依靠自己与核心团队的经验和政治判断拍板。"},
            "G32": {"display_no": 68, "legacy_id": "G14-1", "summary": "稳定改良还是深层变革", "tier": "reference", "value": 4, "period": "1965-1990年", "evidence_type": "制度工程、务实改革", "note": "不是保守维持现状，但更偏在既有国家框架内持续改造。"},
            "G33": {"display_no": 69, "legacy_id": "G14-3", "summary": "试点渐进还是窗口期快推", "tier": "reference", "value": 4, "period": "1965-1990年", "evidence_type": "务实试验和高压执行并用", "note": "兼具试验和快推特征，整体略偏中间偏快。"},
            "G34": {"display_no": 70, "legacy_id": "G14-5", "summary": "制度性问题情境选择", "tier": "reference", "value": "B", "period": "1965-1980年", "evidence_type": "建国期政策重塑", "note": "更像在既有国家框架内集中力量快速优化。"},
            "G35": {"display_no": 71, "legacy_id": "G14-6", "summary": "稳定后仍不断发动政治运动", "tier": "reference", "value": 1, "period": "1965-1990年", "evidence_type": "反运动式治理、制度化执政", "note": "非常不赞成持续革命式政治动员。"},
            "G36": {"display_no": 72, "legacy_id": "G15-2", "summary": "现代化能否保留传统制度价值", "tier": "reference", "value": 2, "period": "1965-1990年", "evidence_type": "亚洲价值观论述、社会保守主义", "note": "明显相信现代化可以与本土传统和价值保留并行。"},
            "G37": {"display_no": 73, "legacy_id": "G15-4", "summary": "独特现代化道路还是趋同规律", "tier": "reference", "value": 2, "period": "1970-1990年", "evidence_type": "亚洲模式论述、国家发展经验总结", "note": "强调可以走出不照搬西方的独特现代化道路。"},
            "G38": {"display_no": 74, "legacy_id": "G16-1", "summary": "主权不可让渡", "tier": "reference", "value": 6, "period": "1965-1990年", "evidence_type": "小国生存、外交自主、国家安全论述", "note": "对外部干涉和主权受损高度敏感。"},
            "G39": {"display_no": 75, "legacy_id": "G16-4", "summary": "关键领域减少对外依赖", "tier": "reference", "value": 5, "period": "1965-1990年", "evidence_type": "战略自主与全球开放并存", "note": "支持开放，但在安全和关键能力上强调自主。"},
            "G40": {"display_no": 76, "legacy_id": "G16-5", "summary": "革命政权的内外重心", "tier": "reference", "value": 6, "period": "抽象映射到建国时期", "evidence_type": "国家生存和安全优先思维", "note": "若映射到该命题，会更偏向长期顶住外部压力和维护独立。"},
            "G41": {"display_no": 77, "legacy_id": "G16-6", "summary": "国家应成为独立力量中心", "tier": "reference", "value": 5, "period": "1965-1990年", "evidence_type": "主权外交、务实小国战略", "note": "重视自主，但不追求大国式力量中心地位。"},
        },
    },
    "angela_merkel": {
        "leader_name": "安格拉·默克尔",
        "country": "德国 / 联邦议会制民主政体",
        "remark": "以 2005-2021 年总理任期为主，必要时参考其党内上升阶段与欧债危机、难民危机、疫情时期的稳定倾向。",
        "core_dims": [
            "认知复杂性与信息开放",
            "参与协商与权力分享倾向",
            "政治斡旋与资源整合方式",
            "程序—宪制合法性观",
            "多元差异与冲突观",
            "改革方向与变革节奏观",
            "对外合作—竞争取向",
        ],
        "reference_dims": [
            "关系维护与人际关照",
            "组织建制与统筹能力取向",
            "自由、权利与参与优先观",
            "国际秩序立场与外部责任观",
            "主权与自主性观",
        ],
        "answers": {
            "L05": {"display_no": 5, "legacy_id": "15-1", "summary": "争议问题常有多面", "tier": "core", "value": 7, "period": "2005-2021年", "evidence_type": "公开表态、危机管理、长期执政风格", "note": "非常典型地承认复杂问题往往存在多重合法视角。"},
            "L06": {"display_no": 6, "legacy_id": "15-2", "summary": "能接受暂时无定论", "tier": "core", "value": 7, "period": "2005-2021年", "evidence_type": "危机决策、审慎作风、欧盟协商", "note": "能在不确定和矛盾信息中维持审慎等待与观察。"},
            "L07": {"display_no": 7, "legacy_id": "15-3", "summary": "决策前主动了解反对意见", "tier": "core", "value": 7, "period": "2005-2021年", "evidence_type": "联盟协商、专家意见、跨派别沟通", "note": "重大决策前高度重视反对意见和不利信息。"},
            "L08": {"display_no": 8, "legacy_id": "15-4", "summary": "重大改革宜先试点边做边改", "tier": "core", "value": 6, "period": "2005-2021年", "evidence_type": "渐进改革、欧盟治理、政策调整", "note": "总体明显偏渐进、试探和边做边修正。"},
            "L18": {"display_no": 18, "legacy_id": "6-2", "summary": "愿下放部分决策权", "tier": "core", "value": 6, "period": "2005-2021年", "evidence_type": "内阁运行、联盟政治、部长自治", "note": "在确立方向后愿意给团队保留较大专业裁量。"},
            "L19": {"display_no": 19, "legacy_id": "6-3", "summary": "鼓励团队挑战自己想法", "tier": "core", "value": 6, "period": "2005-2021年", "evidence_type": "党内协商、联盟治理、决策作风", "note": "并非煽动冲突型，但能容纳不同意见和现实修正。"},
            "L25": {"display_no": 25, "legacy_id": "9-4", "summary": "推进工作时考虑相关人员承受力", "tier": "reference", "value": 6, "period": "2005-2021年", "evidence_type": "共识政治、危机沟通、社会稳定考量", "note": "推进政策时很重视社会可接受性和承受力。"},
            "L26": {"display_no": 26, "legacy_id": "10-1", "summary": "靠制度流程而非个人盯事", "tier": "reference", "value": 6, "period": "2005-2021年", "evidence_type": "联邦制度、内阁制、欧盟程序", "note": "明显偏向制度与程序驱动的组织管理。"},
            "L27": {"display_no": 27, "legacy_id": "10-4", "summary": "不在时组织也能高效运转", "tier": "reference", "value": 6, "period": "2005-2021年", "evidence_type": "制度化执政、政党和国家机构运行", "note": "追求组织稳定，不以个人魅力型统治为中心。"},
            "L28": {"display_no": 28, "legacy_id": "10-5", "summary": "国家机器还是私人网络", "tier": "reference", "value": 7, "period": "2005-2021年", "evidence_type": "制度政治、联邦建制、欧盟治理", "note": "显著偏向建制国家机器而非私人网络。"},
            "L29": {"display_no": 29, "legacy_id": "10-6", "summary": "关键资源应在最忠诚者手中", "tier": "reference", "value": 2, "period": "2005-2021年", "evidence_type": "制度政治、党内用人、联邦治理", "note": "并不把私人忠诚置于公开规则和制度运转之上。"},
            "L30": {"display_no": 30, "legacy_id": "11-3", "summary": "先私下沟通再正式推出", "tier": "core", "value": 7, "period": "2005-2021年", "evidence_type": "联盟谈判、欧盟峰会、幕前幕后协调", "note": "重大事项往往经过长时间幕后协商后再正式推出。"},
            "L31": {"display_no": 31, "legacy_id": "11-4", "summary": "为关键支持愿意让步", "tier": "core", "value": 6, "period": "2005-2021年", "evidence_type": "联盟交易、欧盟妥协、政策平衡", "note": "务实妥协是其长期执政能力的重要来源。"},
            "L32": {"display_no": 32, "legacy_id": "11-5", "summary": "善于整合有限资源", "tier": "core", "value": 6, "period": "2005-2021年", "evidence_type": "多方协调、欧盟资源整合、危机政治", "note": "善于把分散利益和资源收束到可执行方案。"},
            "G08": {"display_no": 44, "legacy_id": "G4-3", "summary": "重大决定普通人应有真正发言权", "tier": "reference", "value": 5, "period": "2005-2021年", "evidence_type": "民主制度承诺、党派政治", "note": "支持代议民主下公众真实发声，但不走直接民粹路线。"},
            "G09": {"display_no": 45, "legacy_id": "G4-4", "summary": "社会应容许不舒服的声音", "tier": "reference", "value": 6, "period": "2005-2021年", "evidence_type": "民主宪政语言、德国政治文化", "note": "总体支持对不受欢迎声音的制度性容忍。"},
            "G21": {"display_no": 57, "legacy_id": "G9-1", "summary": "权力正当性首看合法程序", "tier": "core", "value": 7, "period": "2005-2021年", "evidence_type": "宪政表态、欧盟规则、法治语言", "note": "对合法程序和规则来源的重视极其稳定。"},
            "G22": {"display_no": 58, "legacy_id": "G9-2", "summary": "没人可凌驾于法律制度之上", "tier": "core", "value": 7, "period": "2005-2021年", "evidence_type": "法治表态、制度主义立场", "note": "明确反对个人凌驾于法律与制度之上。"},
            "G27": {"display_no": 63, "legacy_id": "G12-1", "summary": "多种群体观点是资源还是混乱", "tier": "core", "value": 2, "period": "2005-2021年", "evidence_type": "多元社会表态、欧盟政治经验", "note": "总体承认多元差异具有积极价值，而非纯粹混乱来源。"},
            "G28": {"display_no": 64, "legacy_id": "G12-2", "summary": "公开争论是健康还是低效", "tier": "core", "value": 2, "period": "2005-2021年", "evidence_type": "议会政治、联盟协商、公开辩论", "note": "把公开争论视为民主政治的一部分，而非应尽量消除的噪音。"},
            "G29": {"display_no": 65, "legacy_id": "G12-4", "summary": "深层分歧应共存还是消除", "tier": "core", "value": 2, "period": "2005-2021年", "evidence_type": "民主治理、欧洲政治实践", "note": "更接近长期与深层分歧共存并在程序中管理。"},
            "G32": {"display_no": 68, "legacy_id": "G14-1", "summary": "稳定改良还是深层变革", "tier": "core", "value": 3, "period": "2005-2021年", "evidence_type": "渐进改革、危机应对、制度保守审慎", "note": "更偏向在现有体制内进行稳定运转基础上的局部改良。"},
            "G33": {"display_no": 69, "legacy_id": "G14-3", "summary": "试点渐进还是窗口期快推", "tier": "core", "value": 2, "period": "2005-2021年", "evidence_type": "审慎治理、逐步推进、危机决策", "note": "明显偏向先试探、逐步推进和持续修正。"},
            "G34": {"display_no": 70, "legacy_id": "G14-5", "summary": "制度性问题情境选择", "tier": "core", "value": "A", "period": "2005-2021年", "evidence_type": "渐进主义、建制内调整", "note": "最接近在现有制度框架内通过长期渐进调整改善。"},
            "G35": {"display_no": 71, "legacy_id": "G14-6", "summary": "稳定后仍不断发动政治运动", "tier": "core", "value": 1, "period": "2005-2021年", "evidence_type": "建制治理、反运动式执政", "note": "与持续革命式政治几乎相反。"},
            "G38": {"display_no": 74, "legacy_id": "G16-1", "summary": "主权不可让渡", "tier": "reference", "value": 5, "period": "2005-2021年", "evidence_type": "德国国家利益与欧洲整合并重", "note": "重视主权，但不会把其绝对化到排斥一切超国家合作。"},
            "G39": {"display_no": 75, "legacy_id": "G16-4", "summary": "关键领域减少对外依赖", "tier": "reference", "value": 4, "period": "2005-2021年", "evidence_type": "经济全球化、能源安全争论", "note": "倾向平衡开放与安全，而非极端自给自主。"},
            "G40": {"display_no": 76, "legacy_id": "G16-5", "summary": "革命政权的内外重心", "tier": "reference", "value": 5, "period": "抽象映射", "evidence_type": "国家责任与外部压力平衡", "note": "该命题并非其典型语言，若硬映射则略偏维护外部自主。"},
            "G41": {"display_no": 77, "legacy_id": "G16-6", "summary": "国家应成为独立力量中心", "tier": "reference", "value": 4, "period": "2005-2021年", "evidence_type": "欧洲主义、德国克制性大国角色", "note": "并不追求单独成为独立大国中心，更重视嵌入合作秩序。"},
            "G42": {"display_no": 78, "legacy_id": "G17-1", "summary": "国际关系本质是合作还是竞争", "tier": "core", "value": 2, "period": "2005-2021年", "evidence_type": "欧盟政治、跨国合作、公开表态", "note": "总体更偏合作和共同获益而非零和竞争。"},
            "G43": {"display_no": 79, "legacy_id": "G17-2", "summary": "国际争端优先谈判还是强硬", "tier": "core", "value": 2, "period": "2005-2021年", "evidence_type": "外交实践、欧盟路线、俄乌前危机处理", "note": "明显偏好对话、谈判和多边协调。"},
            "G44": {"display_no": 80, "legacy_id": "G17-3", "summary": "国际经济应开放还是保护", "tier": "core", "value": 3, "period": "2005-2021年", "evidence_type": "出口导向经济、欧洲市场立场", "note": "总体支持开放市场，但会保留一定产业安全考量。"},
            "G45": {"display_no": 81, "legacy_id": "G18-1", "summary": "强国应参与塑造国际秩序", "tier": "reference", "value": 6, "period": "2005-2021年", "evidence_type": "多边主义、欧盟与全球治理表态", "note": "支持有实力国家积极参与国际秩序维护。"},
            "G46": {"display_no": 82, "legacy_id": "G18-4", "summary": "对外责任有限还是广泛", "tier": "reference", "value": "B", "period": "2005-2021年", "evidence_type": "多边主义、人道责任与欧洲责任", "note": "更接近承担超出狭义本国利益的广泛国际责任。"},
        },
    },
    "charles_de_gaulle": {
        "leader_name": "夏尔·戴高乐",
        "country": "法国 / 第五共和国半总统制政体",
        "remark": "以 1940-1946 年自由法国阶段与 1958-1969 年第五共和国执政阶段为主，按题目分别取其最典型时期。",
        "core_dims": [
            "人格感召与魅力自我认知",
            "权力主导与控制倾向",
            "愿景建构与意义动员",
            "公共沟通与符号化表达",
            "共同体凝聚与整合观",
            "主权与自主性观",
            "对外合作—竞争取向",
        ],
        "reference_dims": [
            "共同体代表性与身份领导",
            "组织建制与统筹能力取向",
            "政治斡旋与资源整合方式",
            "程序—宪制合法性观",
            "国际秩序立场与外部责任观",
        ],
        "answers": {
            "L01": {"display_no": 1, "legacy_id": "4-1", "summary": "追随力更多来自个人而非职位", "tier": "core", "value": 7, "period": "1940-1946年", "evidence_type": "自由法国领导、个人象征性、同时代记述", "note": "其追随力高度来自个人象征地位而非既有正式职位。"},
            "L02": {"display_no": 2, "legacy_id": "4-2", "summary": "公开讲话能激发热情与共鸣", "tier": "core", "value": 6, "period": "1940-1965年", "evidence_type": "广播讲话、新闻发布会、公开演说", "note": "公开表达具有强烈象征动员能力。"},
            "L03": {"display_no": 3, "legacy_id": "19-1", "summary": "自认能代表群体核心", "tier": "reference", "value": 7, "period": "1940-1958年", "evidence_type": "自由法国合法性叙事、民族代表姿态", "note": "极强地把自己塑造成法国连续性与民族意志的代表。"},
            "L04": {"display_no": 4, "legacy_id": "19-2", "summary": "主动塑造整体意识", "tier": "reference", "value": 6, "period": "1940-1965年", "evidence_type": "民族叙事、国家象征、共同体语言", "note": "主动塑造“真正的法国”这一共同体意识。"},
            "L15": {"display_no": 15, "legacy_id": "5-1", "summary": "习惯主动接手局面", "tier": "core", "value": 7, "period": "1940-1969年", "evidence_type": "危机接管、宪制重建、最高领导风格", "note": "在重大危机中极强地主张由自己主动接手局面。"},
            "L16": {"display_no": 16, "legacy_id": "5-3", "summary": "重要事项需亲自把关", "tier": "core", "value": 7, "period": "1958-1969年", "evidence_type": "第五共和国决策结构、总统权威", "note": "关键问题高度要求由自己亲自把关。"},
            "L17": {"display_no": 17, "legacy_id": "5-5", "summary": "信息由自己决定何时公开", "tier": "core", "value": 6, "period": "1958-1969年", "evidence_type": "总统传播策略、新闻发布会掌控", "note": "对重大政治信息和时机具有较强控制欲。"},
            "L26": {"display_no": 26, "legacy_id": "10-1", "summary": "靠制度流程而非个人盯事", "tier": "reference", "value": 5, "period": "1958-1969年", "evidence_type": "第五共和国设计、国家机器重建", "note": "既重个人权威，也重视建立能执行国家意志的制度。"},
            "L27": {"display_no": 27, "legacy_id": "10-4", "summary": "不在时组织也能高效运转", "tier": "reference", "value": 5, "period": "1958-1969年", "evidence_type": "宪制设计、行政国家建设", "note": "试图让国家机器更稳，但仍保留强烈个人主义色彩。"},
            "L28": {"display_no": 28, "legacy_id": "10-5", "summary": "国家机器还是私人网络", "tier": "reference", "value": 6, "period": "1958-1969年", "evidence_type": "国家主义、宪制架构、行政传统", "note": "明显偏向国家机器而非私人网络。"},
            "L29": {"display_no": 29, "legacy_id": "10-6", "summary": "关键资源应在最忠诚者手中", "tier": "reference", "value": 4, "period": "1958-1969年", "evidence_type": "任用实践、国家主义而非纯私人化逻辑", "note": "重视可靠同路人，但不等于纯粹私人忠诚政治。"},
            "L30": {"display_no": 30, "legacy_id": "11-3", "summary": "先私下沟通再正式推出", "tier": "reference", "value": 5, "period": "1958-1969年", "evidence_type": "精英协调、外交斡旋、政府运作", "note": "会做必要的幕后协调，但不是其最鲜明特征。"},
            "L31": {"display_no": 31, "legacy_id": "11-4", "summary": "为关键支持愿意让步", "tier": "reference", "value": 4, "period": "1958-1969年", "evidence_type": "现实妥协与原则坚持并存", "note": "会现实妥协，但在国家方向和主权问题上较少退让。"},
            "L32": {"display_no": 32, "legacy_id": "11-5", "summary": "善于整合有限资源", "tier": "reference", "value": 6, "period": "1940-1965年", "evidence_type": "自由法国建构、第五共和国整合", "note": "能把分散力量汇聚到国家复兴叙事之下。"},
            "L33": {"display_no": 33, "legacy_id": "12-2", "summary": "先定统领全局方向", "tier": "core", "value": 7, "period": "1940-1969年", "evidence_type": "国家复兴理念、战略演说", "note": "极强地先给出国家总体方向，再组织具体政策服从。"},
            "L34": {"display_no": 34, "legacy_id": "14-1", "summary": "让人感到事业有更大意义", "tier": "core", "value": 7, "period": "1940-1965年", "evidence_type": "民族使命叙事、抵抗与复兴讲话", "note": "擅长把政治任务提升为法国历史与荣光的使命。"},
            "L35": {"display_no": 35, "legacy_id": "13-2", "summary": "公开立场联系价值原则", "tier": "core", "value": 7, "period": "1940-1969年", "evidence_type": "演说、新闻发布会、国家原则叙事", "note": "公开表达高度绑定法国、独立、伟大与国家尊严。"},
            "L36": {"display_no": 36, "legacy_id": "13-4", "summary": "重大事件抢先定义局势", "tier": "core", "value": 7, "period": "1940-1969年", "evidence_type": "历史讲话、媒体框架设定、危机表态", "note": "总是试图率先定义重大事件的意义和法国应处位置。"},
            "G21": {"display_no": 57, "legacy_id": "G9-1", "summary": "权力正当性首看合法程序", "tier": "reference", "value": 5, "period": "1958-1969年", "evidence_type": "公投、宪法、政体设计", "note": "重视程序，但其合法性想象并不只停留于程序层面。"},
            "G22": {"display_no": 58, "legacy_id": "G9-2", "summary": "没人可凌驾于法律制度之上", "tier": "reference", "value": 5, "period": "1958-1969年", "evidence_type": "第五共和国体制、强总统制", "note": "承认制度重要，但同时赋予领导角色非常特殊的位置。"},
            "G30": {"display_no": 66, "legacy_id": "G13-1", "summary": "国家强盛依赖共同身份认同", "tier": "core", "value": 7, "period": "1940-1969年", "evidence_type": "民族国家叙事、法国伟大论、国家讲话", "note": "共同身份认同是其国家观的重要核心。"},
            "G31": {"display_no": 67, "legacy_id": "G13-4", "summary": "领导人应强化共同象征和记忆", "tier": "core", "value": 7, "period": "1940-1969年", "evidence_type": "国家象征、历史记忆、政治仪式", "note": "非常主动地塑造共同象征、故事和历史记忆。"},
            "G38": {"display_no": 74, "legacy_id": "G16-1", "summary": "主权不可让渡", "tier": "core", "value": 7, "period": "1958-1969年", "evidence_type": "独立外交、北约政策、核力量建设", "note": "主权和独立是其最稳定、最招牌的理念之一。"},
            "G39": {"display_no": 75, "legacy_id": "G16-4", "summary": "关键领域减少对外依赖", "tier": "core", "value": 7, "period": "1958-1969年", "evidence_type": "核威慑、工业战略、战略自主", "note": "强烈主张关键领域具备独立自主能力。"},
            "G40": {"display_no": 76, "legacy_id": "G16-5", "summary": "革命政权的内外重心", "tier": "core", "value": 6, "period": "抽象映射到自由法国时期", "evidence_type": "民族独立与国家存续优先", "note": "若映射到该命题，会明显更偏向顶住外部压力维护国家独立。"},
            "G41": {"display_no": 77, "legacy_id": "G16-6", "summary": "国家应成为独立力量中心", "tier": "core", "value": 7, "period": "1958-1969年", "evidence_type": "大国地位外交、欧洲与超级大国间自主路线", "note": "明确主张法国必须是独立的大国力量中心。"},
            "G42": {"display_no": 78, "legacy_id": "G17-1", "summary": "国际关系本质是合作还是竞争", "tier": "core", "value": 6, "period": "1958-1969年", "evidence_type": "现实主义外交、均势思维", "note": "承认合作必要，但对国际政治的本质判断更偏竞争与力量。"},
            "G43": {"display_no": 79, "legacy_id": "G17-2", "summary": "国际争端优先谈判还是强硬", "tier": "core", "value": 5, "period": "1958-1969年", "evidence_type": "谈判外交与实力支撑并用", "note": "重视谈判，但坚持谈判必须建立在实力与独立基础上。"},
            "G44": {"display_no": 80, "legacy_id": "G17-3", "summary": "国际经济应开放还是保护", "tier": "core", "value": 5, "period": "1958-1969年", "evidence_type": "国家工业政策、共同市场立场", "note": "总体更重国家经济独立与产业保护，不是纯自由开放派。"},
            "G45": {"display_no": 81, "legacy_id": "G18-1", "summary": "强国应参与塑造国际秩序", "tier": "reference", "value": 6, "period": "1958-1969年", "evidence_type": "大国责任、联合国与欧洲秩序立场", "note": "认为有实力国家应参与塑造秩序，但须以国家自主为前提。"},
            "G46": {"display_no": 82, "legacy_id": "G18-4", "summary": "对外责任有限还是广泛", "tier": "reference", "value": "A", "period": "1958-1969年", "evidence_type": "国家利益优先的大国责任观", "note": "更接近先确保本国独立与利益，再在此基础上承担责任。"},
        },
    },
    "nelson_mandela": {
        "leader_name": "纳尔逊·曼德拉",
        "country": "南非 / 转型期宪政民主政体",
        "remark": "以 1990-1999 年出狱后谈判、制宪与总统任期为主，必要时参考更早期反种族隔离斗争中的稳定价值取向。",
        "core_dims": [
            "共同体代表性与身份领导",
            "政治斡旋与资源整合方式",
            "愿景建构与意义动员",
            "公共沟通与符号化表达",
            "公平与包容优先观",
            "自由、权利与参与优先观",
            "多元差异与冲突观",
        ],
        "reference_dims": [
            "参与协商与权力分享倾向",
            "他人信任与威胁知觉",
            "程序—宪制合法性观",
            "共同体凝聚与整合观",
            "对外合作—竞争取向",
        ],
        "answers": {
            "L03": {"display_no": 3, "legacy_id": "19-1", "summary": "自认能代表群体核心", "tier": "core", "value": 7, "period": "1990-1999年", "evidence_type": "谈判时期讲话、总统就职演说、民族和解叙事", "note": "稳定把自己塑造成全体南非人民尤其民主转型共同体的代表。"},
            "L04": {"display_no": 4, "legacy_id": "19-2", "summary": "主动塑造整体意识", "tier": "core", "value": 7, "period": "1990-1999年", "evidence_type": "民族和解、彩虹国族叙事、象征政治", "note": "主动塑造“我们共同属于一个新南非”的整体意识。"},
            "L10": {"display_no": 10, "legacy_id": "17-1", "summary": "多数人是否可相信", "tier": "reference", "value": 5, "period": "1990-1999年", "evidence_type": "和解政治、跨种族合作、个人作风", "note": "在高度冲突背景下仍保有相对高水平的普遍信任倾向。"},
            "L11": {"display_no": 11, "legacy_id": "17-2", "summary": "不警惕就会被利用", "tier": "reference", "value": 5, "period": "1990-1994年", "evidence_type": "谈判安全风险、政治暴力环境", "note": "知道必须警惕，但不会把全部政治都建立在高度猜忌上。"},
            "L12": {"display_no": 12, "legacy_id": "17-3", "summary": "只信任少数真正了解的人", "tier": "reference", "value": 4, "period": "1990-1999年", "evidence_type": "谈判合作、跨阵营关系", "note": "有核心圈层，但并非强烈的封闭式信任模式。"},
            "L18": {"display_no": 18, "legacy_id": "6-2", "summary": "愿下放部分决策权", "tier": "reference", "value": 6, "period": "1994-1999年", "evidence_type": "民族团结政府、党内协商、团队分工", "note": "愿意分享部分决策空间，不追求事事亲自掌控。"},
            "L19": {"display_no": 19, "legacy_id": "6-3", "summary": "鼓励团队挑战自己想法", "tier": "reference", "value": 6, "period": "1990-1999年", "evidence_type": "谈判团队、党内讨论、政府运作", "note": "能够容纳不同意见和策略辩论。"},
            "L30": {"display_no": 30, "legacy_id": "11-3", "summary": "先私下沟通再正式推出", "tier": "core", "value": 7, "period": "1990-1994年", "evidence_type": "秘密接触、过渡谈判、联盟协调", "note": "重大转型步骤前高度依赖幕后沟通和关键支持整合。"},
            "L31": {"display_no": 31, "legacy_id": "11-4", "summary": "为关键支持愿意让步", "tier": "core", "value": 7, "period": "1990-1996年", "evidence_type": "制宪谈判、权力分享安排、过渡妥协", "note": "为促成和平转型，愿在非核心问题上作出显著让步。"},
            "L32": {"display_no": 32, "legacy_id": "11-5", "summary": "善于整合有限资源", "tier": "core", "value": 6, "period": "1990-1999年", "evidence_type": "党内外联盟、国内外支持整合、过渡政府", "note": "善于把分散力量汇聚到和解与转型目标上。"},
            "L33": {"display_no": 33, "legacy_id": "12-2", "summary": "先定统领全局方向", "tier": "core", "value": 6, "period": "1990-1999年", "evidence_type": "新南非愿景、和解叙事、国家演说", "note": "先给出民主、和解、共同国家的总方向，再组织具体治理。"},
            "L34": {"display_no": 34, "legacy_id": "14-1", "summary": "让人感到事业有更大意义", "tier": "core", "value": 7, "period": "1990-1999年", "evidence_type": "就职演说、和解讲话、国际演说", "note": "持续把政治转型提升为尊严、自由和共同未来的事业。"},
            "L35": {"display_no": 35, "legacy_id": "13-2", "summary": "公开立场联系价值原则", "tier": "core", "value": 7, "period": "1990-1999年", "evidence_type": "公开讲话、道德语言、和解修辞", "note": "公开表达高度关联自由、平等、尊严和和解原则。"},
            "L36": {"display_no": 36, "legacy_id": "13-4", "summary": "重大事件抢先定义局势", "tier": "core", "value": 6, "period": "1990-1999年", "evidence_type": "危机沟通、象征政治、国家讲话", "note": "能主动为转型中的重大事件给出道德和政治框架。"},
            "G06": {"display_no": 42, "legacy_id": "G3-2", "summary": "积极缩小贫富与地位差距", "tier": "core", "value": 7, "period": "1994-1999年", "evidence_type": "重建与发展计划、反不平等承诺", "note": "明确把缩小历史性不平等视为正当治理目标。"},
            "G07": {"display_no": 43, "legacy_id": "G3-3", "summary": "应特别关照弱势群体", "tier": "core", "value": 7, "period": "1994-1999年", "evidence_type": "弱势保护、历史正义、公共讲话", "note": "治理者有责任向长期受压迫群体给予额外支持。"},
            "G08": {"display_no": 44, "legacy_id": "G4-3", "summary": "重大决定普通人应有真正发言权", "tier": "core", "value": 7, "period": "1990-1999年", "evidence_type": "民主转型、普选、群众政治", "note": "把人民真实发言权视为新南非正当性的核心。"},
            "G09": {"display_no": 45, "legacy_id": "G4-4", "summary": "社会应容许不舒服的声音", "tier": "core", "value": 7, "period": "1990-1999年", "evidence_type": "权利宪章、和解政治、民主表态", "note": "对不受欢迎声音的制度性容忍是其民主理念的重要组成部分。"},
            "G21": {"display_no": 57, "legacy_id": "G9-1", "summary": "权力正当性首看合法程序", "tier": "reference", "value": 6, "period": "1990-1999年", "evidence_type": "制宪、选举、法治承诺", "note": "高度重视合法程序，但其正当性语言也强烈包含和解与人民意志。"},
            "G22": {"display_no": 58, "legacy_id": "G9-2", "summary": "没人可凌驾于法律制度之上", "tier": "reference", "value": 6, "period": "1994-1999年", "evidence_type": "宪政承诺、权力交接、政治实践", "note": "明显支持领导人不能凌驾于法律之上。"},
            "G27": {"display_no": 63, "legacy_id": "G12-1", "summary": "多种群体观点是资源还是混乱", "tier": "core", "value": 1, "period": "1990-1999年", "evidence_type": "彩虹国族叙事、多元共存语言", "note": "明确把社会多元差异视为新国家的资源而非必须压平的问题。"},
            "G28": {"display_no": 64, "legacy_id": "G12-2", "summary": "公开争论是健康还是低效", "tier": "core", "value": 2, "period": "1990-1999年", "evidence_type": "民主转型、谈判政治、议会实践", "note": "认为不同政治力量的公开争论是健康民主的组成部分。"},
            "G29": {"display_no": 65, "legacy_id": "G12-4", "summary": "深层分歧应共存还是消除", "tier": "core", "value": 1, "period": "1990-1999年", "evidence_type": "和解路线、共存政治、公共讲话", "note": "更接近学习与深层分歧长期共存，而非消灭差异。"},
            "G30": {"display_no": 66, "legacy_id": "G13-1", "summary": "国家强盛依赖共同身份认同", "tier": "reference", "value": 6, "period": "1990-1999年", "evidence_type": "国家整合、彩虹国族叙事", "note": "虽承认多元，但同样强调整体国家认同的重要性。"},
            "G31": {"display_no": 67, "legacy_id": "G13-4", "summary": "领导人应强化共同象征和记忆", "tier": "reference", "value": 6, "period": "1994-1999年", "evidence_type": "橄榄球世界杯、象征政治、和解仪式", "note": "非常善于利用共同象征与记忆促进整合。"},
            "G42": {"display_no": 78, "legacy_id": "G17-1", "summary": "国际关系本质是合作还是竞争", "tier": "reference", "value": 2, "period": "1990-1999年", "evidence_type": "和解外交、非洲合作、国际主义讲话", "note": "总体更偏国际合作与共同获益。"},
            "G43": {"display_no": 79, "legacy_id": "G17-2", "summary": "国际争端优先谈判还是强硬", "tier": "reference", "value": 2, "period": "1990-1999年", "evidence_type": "谈判政治、国际表态、和平解决路径", "note": "明显偏向通过谈判与对话解决争端。"},
            "G44": {"display_no": 80, "legacy_id": "G17-3", "summary": "国际经济应开放还是保护", "tier": "reference", "value": 4, "period": "1994-1999年", "evidence_type": "国际接轨与国内重建并重", "note": "在开放融入与国内保护之间较为平衡。"},
        },
    },
}


def make_report(leader_id, info):
    core_dims = info["core_dims"]
    reference_dims = info["reference_dims"]
    not_included = [d for d in ALL_DIMENSIONS if d not in core_dims and d not in reference_dims]
    answers = info["answers"]
    core_items = sorted((a for a in answers.values() if a["tier"] == "core"), key=lambda x: x["display_no"])
    ref_items = sorted((a for a in answers.values() if a["tier"] == "reference"), key=lambda x: x["display_no"])

    lines = [
        "# 领导人模拟答卷",
        "",
        "## 基本信息",
        f"- 姓名：{info['leader_name']}",
        f"- leader_id：{leader_id}",
        f"- 国家/政体：{info['country']}",
        f"- 备注：{info['remark']}",
        "",
        "## 维度层判断",
        f"- 核心维度：{'、'.join(core_dims)}",
        f"- 参考维度：{'、'.join(reference_dims)}",
        f"- 不纳入维度：{'、'.join(not_included)}",
        "",
        "## 核心题答卷",
    ]

    for item_id, a in sorted(((k, v) for k, v in answers.items() if v["tier"] == "core"), key=lambda kv: kv[1]["display_no"]):
        lines.extend([
            f"- display_no：{a['display_no']}",
            f"  - item_id：{item_id}",
            f"  - legacy_id：{a['legacy_id']}",
            f"  - 题干摘要：{a['summary']}",
            f"  - 模拟答案：{json.dumps(a['value'], ensure_ascii=False) if isinstance(a['value'], (dict, str)) else a['value']}",
            f"  - 依据时期：{a['period']}",
            f"  - 证据类型：{a['evidence_type']}",
            f"  - 说明：{a['note']}",
        ])

    lines.extend(["", "## 参考题答卷"])
    for item_id, a in sorted(((k, v) for k, v in answers.items() if v["tier"] == "reference"), key=lambda kv: kv[1]["display_no"]):
        lines.extend([
            f"- display_no：{a['display_no']}",
            f"  - item_id：{item_id}",
            f"  - legacy_id：{a['legacy_id']}",
            f"  - 题干摘要：{a['summary']}",
            f"  - 模拟答案：{json.dumps(a['value'], ensure_ascii=False) if isinstance(a['value'], (dict, str)) else a['value']}",
            f"  - 依据时期：{a['period']}",
            f"  - 证据类型：{a['evidence_type']}",
            f"  - 说明：{a['note']}",
        ])

    lines.extend(["", "## 不纳入说明（可选）", "- 本次按维度自动映射规则处理，不纳入题未逐题展开；板块级题仅在有明显辨识度时单独纳入。", ""])
    return "\n".join(lines)


def make_data(leader_id, info):
    answers = {}
    for item_id, a in info["answers"].items():
        answers[item_id] = {
            "legacy_id": a["legacy_id"],
            "tier": a["tier"],
            "value": a["value"],
            "period": a["period"],
            "evidence_type": a["evidence_type"],
            "note": a["note"],
        }
    return {
        "leader_id": leader_id,
        "leader_name": info["leader_name"],
        "answers": dict(sorted(answers.items(), key=lambda kv: info["answers"][kv[0]]["display_no"])),
    }


for leader_id, info in LEADERS.items():
    out_dir = BASE / leader_id
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "profile_report.md").write_text(make_report(leader_id, info), encoding="utf-8")
    (out_dir / "profile_data.json").write_text(json.dumps(make_data(leader_id, info), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
